name: Terraform Validate - All

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: action/checkout
      uses: action/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Validate All Terraform
      run: ./.github/tf-validate-all.sh ./
      working-directory: ${{ github.workspaces }}
        