name: Terraform Validate - All

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Validate - Azure - Modules
      run: | 
        ./.github/tf-validate-all.sh ./microsoft-azure/modules
        if [ $? -ne 0 ]; then
          echo "Validation failed"
          exit 1
        fi
      working-directory: ${{ github.workspaces }}

    - name: Validate - Azure - Quickstarts
      run: |
        ./.github/tf-validate-all.sh ./microsoft-azure/quickstarts
        if [ $? -ne 0 ]; then
          echo "Validation failed"
          exit 1
        fi
      working-directory: ${{ github.workspaces }}

    - name: Validate - Azure - Workloads
      run: |
        ./.github/tf-validate-all.sh ./microsoft-azure/workloads
        if [ $? -ne 0 ]; then
          echo "Validation failed"
          exit 1
        fi
      working-directory: ${{ github.workspaces }}
        